DB_SCHEMA = """
TABLE `sn` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `value` varchar(255) NOT NULL DEFAULT '' COMMENT 'SN码',
  `mac` varchar(100) DEFAULT NULL COMMENT '本机mac',
  `jpush_id` varchar(30) DEFAULT NULL COMMENT '极光推送ID',
  `appstore_version` varchar(200) DEFAULT NULL COMMENT '设备信息版本号',
  `devices_version` varchar(200) DEFAULT NULL COMMENT '系统固件版本号',
  `store_version` varchar(200) DEFAULT NULL COMMENT '管教易版本号',
  `status` int DEFAULT '1' COMMENT 'SN码状态',
  `createtime` int unsigned NOT NULL DEFAULT '0' COMMENT '上传时间',
  `batch` varchar(20) DEFAULT NULL COMMENT '批次',
  `admin_id` int unsigned NOT NULL DEFAULT '0' COMMENT 'sn码归属id',
  `pid` int DEFAULT NULL COMMENT '父ID',
  `is_delete` tinyint(1) DEFAULT NULL COMMENT '是否删除1是0否',
  `is_reset` tinyint(1) DEFAULT '0' COMMENT '是否重置1是0否',
  `is_pattern` tinyint(1) DEFAULT '0',
  `is_lock` tinyint(1) DEFAULT '1' COMMENT '是否锁定1是0否',
  `update_time` varchar(255) DEFAULT NULL COMMENT '最后一次修改时间',
  `is_online` tinyint(1) DEFAULT '2' COMMENT '是否在线 1是 2否',
  `offlinetime` int DEFAULT NULL COMMENT '离线时间',
  `classlevel` varchar(255) DEFAULT '' COMMENT '班级',
  `sno` varchar(50) DEFAULT '' COMMENT '学号',
  `realname` varchar(50) DEFAULT '' COMMENT '姓名',
  `is_screen_lock` tinyint(1) DEFAULT '0' COMMENT '屏幕锁定   1锁定  0不锁定',
  `phone` varchar(20) DEFAULT NULL COMMENT '监护人1电话',
  `phone_two` varchar(20) DEFAULT NULL COMMENT '监护人2电话',
  `lock_content` varchar(255) DEFAULT '因管控需要，该设备锁定中，请联系老师或管理员' COMMENT '锁屏字幕',
  `is_developer` tinyint(1) DEFAULT '0' COMMENT '开发者模式 0关闭  1开启',
  `platform` varchar(255) DEFAULT NULL COMMENT '平台',
  `local_mac` varchar(255) DEFAULT '' COMMENT '动态mac',
  `is_lock_time` int unsigned DEFAULT '0' COMMENT '加解锁时间',
  `lock_type` tinyint unsigned DEFAULT '0' COMMENT '锁定类型 1是八一项目',
  `reset_time` int unsigned DEFAULT '0',
  `launcher_id` int NOT NULL DEFAULT '0' COMMENT 'launcher主键id',
  `sn_type` tinyint NOT NULL DEFAULT '0' COMMENT '设备类别【1：教管壹B端 2：教管壹C端 3：学习机 4：工业平板】',
  `warranty` tinyint NOT NULL DEFAULT '0' COMMENT '保修时长（按月份存储）',
  `control_time` tinyint NOT NULL DEFAULT '0' COMMENT '管控时长（按月份存储）',
  `platter_id` int NOT NULL DEFAULT '0' COMMENT '学习套餐id 即platter表主键',
  `first_jpush_time` int NOT NULL DEFAULT '0' COMMENT '首次接入极光管控时间',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '其他备注',
  `parent_sn_id` int NOT NULL DEFAULT '0' COMMENT 'parent_sn表主键id ',
  PRIMARY KEY (`id`),
  KEY `sn` (`value`),
  KEY `admin_id` (`admin_id`),
  KEY `is_online` (`is_online`),
  KEY `batch` (`batch`)
) ENGINE=InnoDB AUTO_INCREMENT=121379 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='设备SN';


"""